Database:
  DBType: postgresql
  Username: postgres
  Password: postgres
  Host: localhost
  Port: 5432
  DBName: ckb_explorer_development
  Charset: utf8
  SSLMode: disable
  MaxIdleConns: 10
  MaxOpenConns: 30
App:
  LogSavePath: storage/logs
  LogFileName: app
  LogFileExt: .log
RPC:
  URL: "http://localhost:8114"
  Mode: "mainnet"
SystemCodeHash:
  Dao: "0x82d76d1b75fe2fd9a27dfbaa65a039221a380d76c926f378d3f81cf3e7e13f2e"
  Sudt: "0x5e7a36a77e68eecc013dfa2fe6a23f3b6c344b04005808694ae6dd45eea4cfd5"
