on:
  push:
    tags:
      - 'v*'

name: Create Release

jobs:
  release:
    name: Create Release
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.version }}
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Get current date
        id: current_date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }} (${{ steps.current_date.outputs.date }})
          body_path: ./RELEASENOTES.md
          draft: true
          prerelease: false
      - name: Get version
        id: get_version
        run: echo ::set-output name=version::${GITHUB_REF#refs/*/}
  publish:
    needs: release
    name: Upload Release Asset For ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            artifact_name: ckb-node-websocket-client
            asset_name: ckb-node-websocket-client-${{ needs.release.outputs.version }}-linux-amd64
          - os: windows-latest
            artifact_name: ckb-node-websocket-client.exe
            asset_name: ckb-node-websocket-client-${{ needs.release.outputs.version }}-windows-amd64
          - os: macos-latest
            artifact_name: ckb-node-websocket-client
            asset_name: ckb-node-websocket-client-${{ needs.release.outputs.version }}-macos-amd64
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: |
          go build
          tar zcvf ${{ matrix.asset_name }}.tar.gz ${{ matrix.artifact_name }}
      - name: Upload Release Asset
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
          asset_path: ./${{ matrix.asset_name }}.tar.gz
          asset_name:  ${{ matrix.asset_name }}.tar.gz
          asset_content_type: application/tar+gzip

